package com.automation_tool.controller;

import com.automation_tool.dto.LoginRequestDTO;
import com.automation_tool.dto.RefreshAndAccessTokenDTO;
import com.automation_tool.dto.UserDTO;
import com.automation_tool.service.UserService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import java.util.Map;

@RestController
@RequestMapping("/api/v1/auth")
@Tag(name="User Handling", description = "APIs for handling users")
public class UserController {

    private final UserService userService;
    public UserController(UserService userService) {
        this.userService = userService;
    }

    @PreAuthorize("hasRole('ADMIN')")
    @PostMapping("/register")
    @Operation(summary = "User registration",description="User registration by the admin")
    public ResponseEntity<String> registerUser(@RequestBody UserDTO userDTO) {

        return new ResponseEntity<>(userService.registerUser(userDTO), HttpStatus.OK);
    }

    @PostMapping("/login")
    @Operation(summary="User login",description="user logs in by providing the credentials username and password")
    public ResponseEntity<RefreshAndAccessTokenDTO> loginUser(@RequestBody LoginRequestDTO loginRequestDTO) {

        return new ResponseEntity<>(userService.loginUser(loginRequestDTO),HttpStatus.OK);

    }

    @PostMapping("/logout")
    @Operation(summary="User logout",description="User logs out by providing the tokens for blacklisting")
    public ResponseEntity<String> logoutUser(@RequestBody RefreshAndAccessTokenDTO refreshAndAccessTokenDTO) {

        return new ResponseEntity<>(userService.logoutUser(refreshAndAccessTokenDTO),HttpStatus.OK);

    }

    @PostMapping("/refresh")
    @Operation(summary="Access token generation",description="Access token generated by providing the refresh token")
    public ResponseEntity<Map<String,String>> generateAccessToken(@RequestBody RefreshAndAccessTokenDTO refreshAndAccessTokenDTO) {
        return new ResponseEntity<>(userService.generateAccessToken(refreshAndAccessTokenDTO.refreshToken()),HttpStatus.OK);
    }


}
