
stop-writes-on-bgsave-error no
port 6379
aclfile /opt/bitnami/redis/mounted-etc/users.acl

#persisting on db
#save 900 1
#save 300 10
#save 60 10000

#dir /data
#dbfilename dump.rdb
#stop-writes-on-bgsave-error yes


